from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

from src.dynamic_os.artifact_refs import make_artifact, source_input_refs
from src.dynamic_os.contracts.route_plan import RoleId
from src.dynamic_os.contracts.skill_io import SkillContext, SkillOutput, find_artifact as _find_artifact
from src.dynamic_os.skills.validation import validate_skill_source


_BUILTINS_ROOT = Path(__file__).resolve().parent.parent
_EVOLVED_ROOT = Path.cwd() / "evolved_skills"


def _read_original_skill(skill_id: str) -> tuple[str, str]:
    """Return (run_py_source, skill_yaml_source) for the original skill."""
    skill_dir = _BUILTINS_ROOT / skill_id
    run_py = ""
    skill_yaml = ""
    if (skill_dir / "run.py").is_file():
        run_py = (skill_dir / "run.py").read_text(encoding="utf-8")
    if (skill_dir / "skill.yaml").is_file():
        skill_yaml = (skill_dir / "skill.yaml").read_text(encoding="utf-8")
    return run_py, skill_yaml


def _write_evolved_skill(
    evolved_id: str,
    original_yaml_src: str,
    new_run_py: str,
    original_skill_id: str,
) -> Path:
    evolved_dir = _EVOLVED_ROOT / evolved_id
    evolved_dir.mkdir(parents=True, exist_ok=True)

    if original_yaml_src:
        parsed = yaml.safe_load(original_yaml_src)
        parsed["id"] = evolved_id
        parsed["name"] = parsed.get("name", evolved_id) + " (evolved)"
        yaml_content = yaml.dump(parsed, default_flow_style=False, allow_unicode=True)
    else:
        yaml_content = (
            f"id: {evolved_id}\nname: {evolved_id}\nversion: 1.0.0\n"
            f"applicable_roles: [experimenter]\ndescription: Evolved version of {original_skill_id}\n"
            f"input_contract:\n  required: []\n  optional: []\noutput_artifacts: []\n"
            f"allowed_tools: [mcp.llm.chat]\npermissions: {{}}\ntimeout_sec: 120\n"
        )

    (evolved_dir / "skill.yaml").write_text(yaml_content, encoding="utf-8")
    (evolved_dir / "run.py").write_text(new_run_py, encoding="utf-8")
    (evolved_dir / "skill.md").write_text(
        f"Evolved version of `{original_skill_id}`. Auto-generated by optimize_skill.\n",
        encoding="utf-8",
    )
    return evolved_dir


def _extract_python_block(text: str) -> str:
    match = re.search(r"```python\s*\n(.*?)```", text, re.DOTALL)
    if match:
        return match.group(1).strip()
    match = re.search(r"```\s*\n(.*?)```", text, re.DOTALL)
    if match:
        return match.group(1).strip()
    return text.strip()


async def run(ctx: SkillContext) -> SkillOutput:
    report = _find_artifact(ctx, "ReflectionReport")
    if report is None:
        return SkillOutput(success=False, error="optimize_skill requires a ReflectionReport input artifact")

    failed_skill_id = report.payload.get("failed_skill_id", "")
    if not failed_skill_id:
        return SkillOutput(success=False, error="ReflectionReport missing failed_skill_id")

    original_run_py, original_yaml = _read_original_skill(failed_skill_id)
    if not original_run_py:
        return SkillOutput(success=False, error=f"Cannot read source for skill: {failed_skill_id}")

    raw = await ctx.tools.llm_chat(
        [
            {
                "role": "system",
                "content": (
                    "You are a skill code optimizer for a multi-agent research system. "
                    "Given the original skill source and a failure analysis, produce an improved "
                    "version of the run.py that fixes the identified issues. "
                    "Output ONLY the complete new run.py content in a Python code block. "
                    "Keep the same function signature: async def run(ctx: SkillContext) -> SkillOutput. "
                    "Keep all existing imports and adapt as needed."
                ),
            },
            {
                "role": "user",
                "content": (
                    f"## Reflection Report\n"
                    f"Root cause: {report.payload.get('root_cause', '')}\n"
                    f"Category: {report.payload.get('failure_category', '')}\n"
                    f"Suggested fix: {report.payload.get('suggested_fix', '')}\n\n"
                    f"## Original run.py\n```python\n{original_run_py}\n```"
                ),
            },
        ],
        temperature=0.2,
        max_tokens=8192,
    )

    new_source = _extract_python_block(raw)
    errors = validate_skill_source(new_source)
    if errors:
        return SkillOutput(
            success=False,
            error=f"Generated code failed validation: {'; '.join(errors)}",
            metadata={"raw_output": raw[:2000]},
        )

    evolved_id = f"{failed_skill_id}_evolved"
    evolved_dir = _write_evolved_skill(evolved_id, original_yaml, new_source, failed_skill_id)

    payload = {
        "original_skill_id": failed_skill_id,
        "evolved_skill_id": evolved_id,
        "evolved_path": str(evolved_dir),
        "diff_summary": report.payload.get("suggested_fix", ""),
        "validation_passed": True,
        "requires_registry_refresh": True,
    }

    artifact = make_artifact(
        node_id=ctx.node_id,
        artifact_type="SkillPatch",
        producer_role=RoleId(ctx.role_id),
        producer_skill=ctx.skill_id,
        payload=payload,
        source_inputs=source_input_refs(ctx.input_artifacts),
    )
    return SkillOutput(
        success=True,
        output_artifacts=[artifact],
        metadata={"requires_registry_refresh": True},
    )
